final/analyse/urls.py
from django.urls import path
from .import views

app_name = 'analyse'
urlpatterns = [
    path('importer_fichier2/', views.importer_fichier2, name="importer_fichier2"),
    # path('traitement_affichage/<colonnes>/<graphe>/', views.traitement_affichage, name='traitement_affichage'),
    # path('traitement_affichage/', views.traitement_affichage, name="traitement_affichage"),
    path('appliquer_test_statistique/', views.appliquer_test_statistique, name="appliquer_test_statistique")
]

final/calcule/urls.py
from django.urls import path
from . import views

app_name = 'calcule'
urlpatterns = [
path('', views.statistics, name='statistics'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('calcule/', include('calcule.urls')),
    path('matapp/', include('matapp.urls')),
    path('analyse/', include('analyse.urls')),
    path('proba/', include('proba.urls')),
    path('', include('calcule.urls')),
]

final/matapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'matapp'
urlpatterns = [
    path('',views.upload,name="upload"),
]

final/proba/urls.py
from django.urls import path
from .views import upload_file

app_name = 'proba'
urlpatterns = [
    path('', upload_file, name="upload_file"),
]

final/calcule/models.py
from django.db import models

# Create your models here.

final/calcule/forms.py
from django import forms
class UploadForm(forms.Form):
    filename = forms.FileField()
    column_name = forms.CharField()
    operation_choices = [('min', 'Min'), ('max', 'Max'), ('mode', 'Mode'), ('median', 'Median'), ('mean', 'Mean'),('sum', 'Somme'),
    ('std', 'Ecartype'),('etendu', 'Etendu'),]
    operation = forms.ChoiceField(choices=operation_choices)
    display_option_choices = [('head', 'Show Entire Head'), ('custom', 'Show Custom Range')]
    display_option = forms.ChoiceField(choices=display_option_choices)
    custom_lines = forms.CharField(required=False)

final/calcule/views.py
from django.shortcuts import render
from django.http import HttpResponse
import pandas as pd
from .forms import UploadForm

def statistics(request):
    form = UploadForm()
    df_head_display = None
    result_display = None

    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_file = form.cleaned_data.get('filename')

            if uploaded_file:
                if uploaded_file.name.endswith('.csv'):
                    df = pd.read_csv(uploaded_file)
                elif uploaded_file.name.endswith('.xlsx'):
                    df = pd.read_excel(uploaded_file)
                else:
                    return HttpResponse('Format de fichier non pris en charge. Veuillez télécharger un fichier CSV ou Excel.')

                # Display df.head() or custom range on the same page
                display_option = form.cleaned_data['display_option']
                if display_option == 'head':
                    df_head_display = df.head().to_html()
                elif display_option == 'custom':
                    custom_lines = form.cleaned_data['custom_lines']
                    try:
                        start, end = map(int, custom_lines.split(':'))
                        df_head_display = df.iloc[start:end+1].to_html()
                    except (ValueError, IndexError):
                        df_head_display = "Veuillez entrer un intervalle valide."

                # Perform operation
                column_name = form.cleaned_data['column_name']
                operation = form.cleaned_data['operation']

                try:
                    if operation == 'mode':
                        result = df[column_name].mode()
                    elif operation == 'median':
                        result = df[column_name].median()
                    elif operation == 'mean':
                        result = df[column_name].mean()
                    elif operation == 'sum':
                        result = df[column_name].sum()
                    elif operation == 'std':
                        result = df[column_name].std()
                    elif operation == 'etendu':
                        result = df[column_name].max() - df[column_name].min()
                    else:
                        result = getattr(df[column_name], operation)()
                
                    result_display = f"le {operation} de le colonne'{column_name}' est: {result}"
                except (KeyError, AttributeError):
                    result_display = f"Invalid column name: {column_name}"

    return render(request, 'statistics.html', {'form': form, 'df_head_display': df_head_display, 'result_display': result_display})

final/calcule/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif; /* Choisissez la police de caractères de votre choix */
        }
    
        nav {
                background-color: lightblue;
                padding: 15px;
                text-align: center;
            }

            nav ul {
                list-style: none;
                margin: 0;
                padding: 0;
            }

            nav ul li {
                display: inline;
                margin-right: 30px; /* Ajout d'une marge à droite pour séparer les liens */
            }

            nav a {
                text-decoration: none;
                color: black;
                font-weight: bold;
                font-size: 18px;
            }

    
        div {
            padding: 20px;
        }
    </style>
    
</head>
<body>

<nav>
    <ul>
        <li><a href="{% url 'calcule:statistics' %}">calcule statistique</a></li>
        <li><a href="{% url 'matapp:upload' %}">visualisation des données</a></li>
        <li><a href="{% url 'analyse:importer_fichier2' %}">test des hypothèses</a></li>
        <li><a href="{% url 'proba:upload_file' %}">loi de probabilité</a></li>
    </ul>
</nav>

<div>
    {% block content %}{% endblock %}
</div>

</body>
</html>

final/calcule/templates/statistics.html
<!DOCTYPE html>
<html>
<head>
    <title>manipulation de données</title>
    {% extends 'base.html' %}
    {% load static %}
    
    {% block content %}
    <style>
                  body {
                    background-color: #add8e6; /* Your existing background color */
                    background-image: url("{% static 'background1.jpg' %}"); 
                }

                form {
                    width: 50%;
                    margin: 50px auto;
                    padding: 30px;
                    border: 1px solid #ddd;
                    background-color: #fff;
                    border-radius: 10px;
                    box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);
                }

                label {
                    display: block;
                    margin-bottom: 10px;
                    font-size: 16px;
                    color: #333;
                }

                input[type="text"],
                input[type="file"] {
                    width: calc(100% - 22px);
                    padding: 10px;
                    margin-bottom: 15px;
                    border: 1px solid #ccc;
                    border-radius: 5px;
                    font-size: 16px;
                }

                input[type="checkbox"] {
                    margin-bottom: 15px;
                }

                input[type="submit"] {
                    background-color: #007bff;
                    color: white;
                    padding: 15px 20px;
                    border: none;
                    border-radius: 5px;
                    cursor: pointer;
                    font-size: 18px;
                    transition: background-color 0.3s;
                }

                input[type="submit"]:hover {
                    background-color: #0056b3;
                }
                .result-container {
                        width: 50%;
                        margin: 50px auto;
                        padding: 30px;
                        border: 1px solid #fff; /* White border */
                        background-color: #fff;
                        border-radius: 10px;
                        box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
                        text-align: center; /* Center the text */
                    }

                    /* CSS for the result heading */
                    .result-container h4 {
                        color: #007bff; /* Blue color for the heading */
                    }

    </style>
     <script>
        function displayColumns() {
            var input = document.getElementById("id_filename");
            var file = input.files[0];

            if (file) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    // Extract column names (header) from the CSV or Excel file
                    var header = e.target.result.split('\n')[0];
                    var columnNames = header.split(',');

                    var ul = document.createElement("ul");
                    columnNames.forEach(function(columnName) {
                        var li = document.createElement("li");
                        li.appendChild(document.createTextNode(columnName.trim()));
                        ul.appendChild(li);
                    });

                    document.getElementById("column_names_display").innerHTML = "<h3>Noms des colonnes</h3>";
                    document.getElementById("column_names_display").appendChild(ul);
                };
                reader.readAsText(file);
            }
        }
    </script>
</head>
<body>
    <h2>Calcul statistique Min/Max/Mode/Median/Mean</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="filename" id="id_filename" accept=".csv, .xlsx" onchange="displayColumns()">
        <div id="column_names_display"></div>
        <br>
        <label for="id_display_option">Option d'affichage :</label>
        <select name="display_option" id="id_display_option">
            <option value="head">Afficher de head</option>
            <option value="custom">Afficher spécifiques lignes</option>
        </select>
        <label for="id_custom_lines">Intervalle (si sélectionnées) :</label>
        <input type="text" name="custom_lines" id="id_custom_lines">
        <label for="id_column_name">Nom de colonne:</label>
        <input type="text" name="column_name" id="id_column_name">
        <label for="id_operation">Operation:</label>
        <select name="operation" id="id_operation">
            <option value="min">Min</option>
            <option value="max">Max</option>
            <option value="mode">Mode</option>
            <option value="median">Median</option>
            <option value="mean">Mean</option>
            <option value="sum">Somme</option>
            <option value="std">Ecartype</option>
            <option value="etendu">Etendu</option>
        </select>
        <button type="submit">Submit</button>
    </form>

    {% if df_head_display %}
        <div class="result-container">
            <h3>DataFrame</h3>
            {{ df_head_display|safe }}
        </div>
    {% endif %}

    {% if result_display %}
        <div class="result-container">
            <h4>Résultat</h4>
            {{ result_display }}
        </div>
    {% endif %}
</body>
{% endblock %}
</html>