final/analyse/urls.py
from django.urls import path
from .import views

app_name = 'analyse'
urlpatterns = [
    path('importer_fichier2/', views.importer_fichier2, name="importer_fichier2"),
    # path('traitement_affichage/<colonnes>/<graphe>/', views.traitement_affichage, name='traitement_affichage'),
    # path('traitement_affichage/', views.traitement_affichage, name="traitement_affichage"),
    path('appliquer_test_statistique/', views.appliquer_test_statistique, name="appliquer_test_statistique")
]

final/calcule/urls.py
from django.urls import path
from . import views

app_name = 'calcule'
urlpatterns = [
path('', views.statistics, name='statistics'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('calcule/', include('calcule.urls')),
    path('matapp/', include('matapp.urls')),
    path('analyse/', include('analyse.urls')),
    path('proba/', include('proba.urls')),
    path('', include('calcule.urls')),
]

final/matapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'matapp'
urlpatterns = [
    path('',views.upload,name="upload"),
]

final/proba/urls.py
from django.urls import path
from .views import upload_file

app_name = 'proba'
urlpatterns = [
    path('', upload_file, name="upload_file"),
]

final/matapp/models.py
from django.db import models

# Create your models here.

final/matapp/forms.py
from django import forms
class UploadForm(forms.Form):
    filename = forms.FileField()
    column_name1 = forms.CharField(required=False)
    column_name2 = forms.CharField(required=False)
    operation_choices = [('lineplot', 'lineplot'), ('scatterplot', 'scatterplot'),('boxplot', 'boxplot'),
                          ('hisplot', 'hisplot'),('kdeplot', 'kdeplot'), ('violinplot', 'violinplot'),
                          ('barplot', 'barplot'), ('heatmap', 'heatmap'),
                          ('Piechart', 'Piechart'), ('Countplot', 'Countplot')]
    operation = forms.ChoiceField(choices=operation_choices)
    

final/matapp/views.py
from django.http import HttpResponse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import urllib.parse
import base64
import io
from django.shortcuts import render
from .forms import UploadForm

def upload(request):
    form = UploadForm()
    result_display = None
    data_uri = None

    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            uploaded_file = form.cleaned_data.get('filename')

            if uploaded_file:
                try:
                    if uploaded_file.name.endswith('.csv'):
                        df = pd.read_csv(uploaded_file)
                    elif uploaded_file.name.endswith('.xlsx'):
                        df = pd.read_excel(uploaded_file)
                    else:
                        return HttpResponse('Format de fichier non pris en charge. Veuillez télécharger un fichier CSV ou Excel.')

                    column_types = df.dtypes
                    numeric_columns = column_types[column_types.apply(lambda x: np.issubdtype(x, np.number))].index
                    categorical_columns = column_types[column_types == 'object'].index

                    column_name1 = form.cleaned_data['column_name1']
                    column_name2 = form.cleaned_data['column_name2']
                    operation = form.cleaned_data['operation']

                    if operation == 'lineplot':
                        if column_name1 not in numeric_columns or column_name2 not in numeric_columns:
                            return HttpResponse('Les colonnes sélectionnées doivent être numériques pour un Line Plot.')
                        else:
                            plt.figure(figsize=(10, 6))
                            sns.lineplot(x=column_name1, y=column_name2, data=df, marker='o', color='b', label='V')
                            plt.xlabel(column_name1)
                            plt.ylabel(column_name2)
                            plt.title(f"Line Plot of {column_name1} and {column_name2}")

                    elif operation == 'scatterplot':
                        if column_name1 not in numeric_columns or column_name2 not in numeric_columns:
                            return HttpResponse('Les colonnes sélectionnées doivent être numériques pour un scatter Plot.')
                        else:
                        # Create a scatter plot
                            plt.figure(figsize=(10, 6))
                            sns.scatterplot(x=column_name1, y=column_name2, data=df, marker='o', color='b', label='V')
                            plt.xlabel(column_name1)
                            plt.ylabel(column_name2)
                            plt.title(f"Scatter Plot of {column_name1} vs {column_name2}")

                    elif operation == 'boxplot':
                        if column_name2 not in numeric_columns or column_name1 not in categorical_columns :
                            return HttpResponse('Les colonnes sélectionnées doivent être x catégorique et y numériques pour un Box Plot.')
                        else:
                            # Create a scatter plot
                            plt.figure(figsize=(10, 6))
                            #sns.boxplot(x=column_name1, y=column_name2, data=df, marker='o', color='b', label='V')
                            sns.boxplot(x=column_name1, y=column_name2, data=df)
                            plt.xlabel(column_name1)
                            plt.ylabel(column_name2)
                            plt.title(f"Box Plot of {column_name1} vs {column_name2}")
                        
                            

                    elif operation == 'hisplot':
                        if column_name1 not in numeric_columns:
                            return HttpResponse('La colonne sélectionnée doit être  numériques pour un Histogram Plot.')
                        else:
                            sns.set()  # or sns.set(style="whitegrid")
                            plt.figure(figsize=(10, 6))
                            sns.histplot(data=df, x=column_name1)
                            plt.xlabel(column_name1)
                            plt.ylabel("Count")
                            plt.title(f"Histogram of {column_name1}")
                    
                    elif operation == 'kdeplot':
                        if column_name1 not in numeric_columns:
                            return HttpResponse('La colonne sélectionnée doit être  numériques pour un KDE Plot.')
                        else:
                            sns.set()  # or sns.set(style="whitegrid")
                            plt.figure(figsize=(10, 6))
                            sns.kdeplot(data=df, x=column_name1, fill=True)
                            plt.xlabel(column_name1)
                            plt.ylabel("Density")
                            plt.title(f"KDE of {column_name1}")
                    
                    elif operation == 'violinplot':
                        sns.set()  # or sns.set(style="whitegrid")
                        plt.figure(figsize=(10, 6))
                        sns.violinplot(data=df, x=column_name1)
                        plt.xlabel(column_name1)
                        plt.title(f"Violin of {column_name1}")

                    elif operation == 'barplot':
                        if  column_name2 not in numeric_columns:
                            return HttpResponse('Les colonnes sélectionnées doivent être x catégorique ou numérique et y numériques pour un Bar Plot.')
                        else:
                            sns.set()  # or sns.set(style="whitegrid")
                            plt.figure(figsize=(10, 6))
                            sns.barplot(data=df, x=column_name1, y=column_name2)
                            plt.xlabel(column_name1)
                            plt.ylabel(column_name2)
                            plt.title(f"Bar plot of {column_name1} and {column_name2}")

                    elif operation == 'heatmap':
                        df_num = df.select_dtypes(include=['number'])
                        sns.heatmap(df_num.corr())
                        plt.title(f" Heatmap:")

                    elif operation == 'Piechart':
                        if column_name1 not in categorical_columns:
                            return HttpResponse('La colonne sélectionnée pour le Pie Chart doit être catégorique.')

                        plt.figure(figsize=(10, 6))
                        
                        # Get counts for each category in the selected column
                        counts = df[column_name1].value_counts()
                        
                        # Extract labels and values for the pie chart
                        labels = counts.index
                        values = counts.values
                        
                        plt.pie(values, labels=labels, autopct='%1.1f%%', startangle=140)
                        plt.title(f"Pie Chart of {column_name1}")

                    elif operation == 'Countplot':
                        if  column_name1 not in categorical_columns:
                            return HttpResponse('La colonne sélectionnée doit être catégorique  pour un Count Plot.')
                        else:
                            sns.set()  # or sns.set(style="whitegrid")
                            plt.figure(figsize=(10, 6))
                            sns.countplot(data=df, x=column_name1)
                            plt.xlabel(column_name1)
                            plt.ylabel("Count")
                            plt.title(f"Count plot of {column_name1}")


                    # Save the plot to a buffer
                    buf = io.BytesIO()
                    plt.savefig(buf, format='png')
                    buf.seek(0)

                    # Convert the plot to base64 and encode it
                    string = base64.b64encode(buf.read()).decode('utf-8')
                    data_uri = urllib.parse.quote(string)

                    # Close the plot
                    plt.close()

                    #result_display = "Calcul réussi !"

                except (pd.errors.EmptyDataError, pd.errors.ParserError, KeyError, AttributeError) as e:
                    result_display = f"Error processing file: {str(e)}"

    return render(request, 'upload.html', {'form': form, 'data': data_uri, 'result_display': result_display})

final/matapp/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif; /* Choisissez la police de caractères de votre choix */
        }
    
        nav {
                background-color: lightblue;
                padding: 15px;
                text-align: center;
            }

            nav ul {
                list-style: none;
                margin: 0;
                padding: 0;
            }

            nav ul li {
                display: inline;
                margin-right: 30px; /* Ajout d'une marge à droite pour séparer les liens */
            }

            nav a {
                text-decoration: none;
                color: black;
                font-weight: bold;
                font-size: 18px;
            }

    
        div {
            padding: 20px;
        }
    </style>
    
</head>
<body>

<nav>
    <ul>
        <li><a href="{% url 'calcule:statistics' %}">calcule statistique</a></li>
        <li><a href="{% url 'matapp:upload' %}">visualisation des données</a></li>
        <li><a href="{% url 'analyse:importer_fichier2' %}">test des hypothèses</a></li>
        <li><a href="{% url 'proba:upload_file' %}">loi de probabilité</a></li>
    </ul>
</nav>

<div>
    {% block content %}{% endblock %}
</div>

</body>
</html>

final/matapp/templates/home.html
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>matapp</title>
    </head>
    <body>
        <h1>Visualisation de données</h1>
        <img src="data:image/png;base64,{{data}}" alt="" height="600" ,width="600">
    </body>
</html>

final/matapp/templates/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Visualisation de données</title>
    {% extends 'base.html' %}
    {% load static %}
    
    {% block content %}
    <style>
                  body {
                    background-color: #add8e6; /* Your existing background color */
                    background-image: url("{% static 'background1.jpg' %}");
                    
                    
                }

                form {
                    width: 50%;
                    margin: 50px auto;
                    padding: 30px;
                    border: 1px solid #ddd;
                    background-color: #fff;
                    border-radius: 10px;
                    box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);  /* Light blue shadow */
                }

                label {
                    display: block;
                    margin-bottom: 10px;
                    font-size: 16px;
                    color: #333;
                }

                input[type="text"],
                input[type="file"] {
                    width: calc(100% - 22px);
                    padding: 10px;
                    margin-bottom: 15px;
                    border: 1px solid #ccc;
                    border-radius: 5px;
                    font-size: 16px;
                }

                input[type="checkbox"] {
                    margin-bottom: 15px;
                }

                input[type="submit"] {
                    background-color: #007bff;
                    color: white;
                    padding: 15px 20px;
                    border: none;
                    border-radius: 5px;
                    cursor: pointer;
                    font-size: 18px;
                    transition: background-color 0.3s;
                }

                input[type="submit"]:hover {
                    background-color: #0056b3;
                }
                select {
                    padding: 8px;
                    font-size: 16px;
                    border: 1px solid #ccc;
                    border-radius: 4px;
                    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                    outline: none;
                    transition: border-color 0.3s ease;
                    }

                    /* Style the options */
                    select option {
                    padding: 10px;
                    }

                    /* Change styles on hover and focus */
                    select:hover,
                    select:focus {
                    border-color: #007bff; /* Change to your desired highlight color */
                    }

                    /* Customize the arrow icon */
                    select::-ms-expand {
                    display: none;
                    }

                    select::after {
                    content: '\25BC'; /* Unicode character for down arrow */
                    position: absolute;
                    top: 50%;
                    right: 10px;
                    transform: translateY(-50%);
                    pointer-events: none;
                    }
                    /* CSS for the result display container */
                    .result-container {
                        width: 80%;
                        margin: 50px auto;
                        padding: 30px;
                        border: 1px solid #fff; /* White border */
                        background-color: #fff;
                        border-radius: 10px;
                        box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
                        text-align: center; /* Center the text */
                    }

                    /* CSS for the result heading */
                    .result-container h4 {
                        color: #007bff; /* Blue color for the heading */
                    }


    </style>
     <script>
        function displayColumns() {
            var input = document.getElementById("id_filename");
            var file = input.files[0];

            if (file) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    // Extract column names (header) from the CSV or Excel file
                    var header = e.target.result.split('\n')[0];
                    var columnNames = header.split(',');

                    var ul = document.createElement("ul");
                    columnNames.forEach(function(columnName) {
                        var li = document.createElement("li");
                        li.appendChild(document.createTextNode(columnName.trim()));
                        ul.appendChild(li);
                    });

                    document.getElementById("column_names_display").innerHTML = "<h3>Noms des colonnes</h3>";
                    document.getElementById("column_names_display").appendChild(ul);
                };
                reader.readAsText(file);
            }
        }
    </script>
</head>
<body>
    <h2>Visualisation de données</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'matapp:upload' %}">
        {% csrf_token %}
        <input type="file" name="filename" id="id_filename" accept=".csv, .xlsx" onchange="displayColumns()">
        <div id="column_names_display"></div>
        <br>
        <label for="id_column_name1">Nom de colonne 1 :</label>
        <input type="text" name="column_name1" id="id_column_name1">
        <label for="id_column_name2 ">Nom de colonne 2:</label>
        <input type="text" name="column_name2" id="id_column_name2">
        <label for="id_operation">Operation:</label>
        <select name="operation" id="id_operation">
            <option value="lineplot">line plot</option>
            <option value="scatterplot">Scatter plot</option>
            <option value="boxplot">Box plot</option>
            <option value="hisplot">Histogram plot</option>
            <option value="kdeplot">KDE plot</option>
            <option value="violinplot">violin plot</option>
            <option value="barplot">bar plot</option>
            <option value="heatmap">heatmap</option>
            <option value="Piechart">Pie Chart</option>
            <option value="Countplot">Count Plot</option>
        </select>
        <button type="submit">Submit</button>
    </form>
    

    {% if data %}
        <div class="result-container">
            <h4>Statistical Plot</h4>
            <img src="data:image/png;base64,{{ data }}" alt="Statistical Plot">
        </div>
    {% endif %}

    {% if result_display %}
    
        <h4>Result</h4>
        {{ result_display }}
    {% endif %}
</body>
{% endblock %}
</html>