final/analyse/urls.py
from django.urls import path
from .import views

app_name = 'analyse'
urlpatterns = [
    path('importer_fichier2/', views.importer_fichier2, name="importer_fichier2"),
    # path('traitement_affichage/<colonnes>/<graphe>/', views.traitement_affichage, name='traitement_affichage'),
    # path('traitement_affichage/', views.traitement_affichage, name="traitement_affichage"),
    path('appliquer_test_statistique/', views.appliquer_test_statistique, name="appliquer_test_statistique")
]

final/calcule/urls.py
from django.urls import path
from . import views

app_name = 'calcule'
urlpatterns = [
path('', views.statistics, name='statistics'),
]

final/final/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('calcule/', include('calcule.urls')),
    path('matapp/', include('matapp.urls')),
    path('analyse/', include('analyse.urls')),
    path('proba/', include('proba.urls')),
    path('', include('calcule.urls')),
]

final/matapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'matapp'
urlpatterns = [
    path('',views.upload,name="upload"),
]

final/proba/urls.py
from django.urls import path
from .views import upload_file

app_name = 'proba'
urlpatterns = [
    path('', upload_file, name="upload_file"),
]

final/analyse/models.py
from django.db import models

# Create your models here.

final/analyse/views.py
from io import BytesIO, StringIO
from django.shortcuts import render, redirect
from django.http import HttpResponse
import numpy as np
import pandas as pd
from analyse.graphes_visualisations import*
from scipy.stats import norm, t
import matplotlib.pyplot as plt
import chardet

def importer_fichier2(request):

    if request.method == 'POST':
        fichier = request.FILES.get('fichier')
        encodings = [
            "ISO-8859-1",  # Latin-1
            "ISO-8859-15", # Latin-9
            "Windows-1252", # Commonly used in Windows systems
            "ISO-8859-2",  # Latin-2
            "ISO-8859-3",  # Latin-3
            "ISO-8859-4",  # Latin-4
            "ISO-8859-5",  # Latin/Cyrillic
            "ISO-8859-6",  # Latin/Arabic
            "ISO-8859-7",  # Latin/Greek
            "ISO-8859-8",  # Latin/Hebrew
            "ISO-8859-9",  # Latin-5
            "ISO-8859-10", # Latin-6
            "ISO-8859-11", # Latin/Thai
            "ISO-8859-13", # Latin-7
            "ISO-8859-14", # Latin-8
            "ISO-8859-16", # Latin-10
            ]
        if est_utf8(fichier) in encodings:
            return HttpResponse(f"L'encodage du fichier ({est_utf8(fichier)}) n'est pas supporté")
        else:
            pass
            
        if fichier:
            if fichier.name.endswith('.xlsx'):
                return HttpResponse("Veuillez uploader un fichier CSV.")
                # df = pd.read_excel(fichier)
            elif fichier.name.endswith('.csv'):
                df = pd.read_csv(fichier)
        else:
            return HttpResponse("Veuillez uploader un fichier CSV.")

        # Convertion le dataframe en HTML
        df_html = df.head().to_html(index=False, float_format='%.2f')

        # Stocker les noms de colonnes dans la session
        request.session['df_columns'] = df.columns.tolist()

        df_json = df.to_json()
        request.session['df_data'] = df_json

        # Création des cases à cocher pour les colonnes
        # checkboxes = ''.join([f'<input type="checkbox" name="col_checkbox" value="{col}" id="chk_{col}"><label for="chk_{col}">{col}</label><br>' for col in df.columns])
        # Création des boutons radio pour les colonnes
        radio_buttons = ''.join([f'<input type="radio" name="colonne" value="{col}" id="radio_{col}"><label for="radio_{col}">{col}</label><br>' for col in df.columns])

        operateurs = [
                '=', 
                '>',
                '<',
                '>=', 
                '<=', 
                '!='
            ]

        # Passage du HTML du dataframe et les cases à cocher au contexte
        context = {'df_html': df_html, 'radio_buttons': radio_buttons, 'operateurs': operateurs}

        return render(request, 'affichage.html', context)
              
    else:
        return render(request, 'upload1.html')
    
def appliquer_test_statistique(request):
    if 'submit_choix' in request.POST:
        if request.method == 'POST':
            colonne = request.POST.get('colonne')
             # Récupération le DataFrame stocké dans la session sous forme de JSON
            df_json = request.session.get('df_data')
            if df_json:
                # Reconstruction le DataFrame à partir de la chaîne JSON
                df = pd.read_json(StringIO(df_json))

                # Obtention toutes les valeurs de la colonne sélectionnée
                valeurs_colonne = df[colonne].tolist()
                    
        if not colonne:
            return HttpResponse("Aucune donnée de dataframe trouvée.")
        
        # Vérification si la taille de l'échantillon est supérieure ou égale à la taille de la population
        taille_echantillon = int(request.POST.get('taille_echantillon'))
        if taille_echantillon >= len(df):
            return HttpResponse("La taille de l'échantillon ne peut pas être supérieure ou égale au nombre total de lignes dans les données.", status=400)

        # Vérification si les valeurs de la colonne sont numériques
        if numerique_ou_non(valeurs_colonne) == False:
            return HttpResponse(f"Les valeurs de la colonne '{colonne}' ne peuvent pas être converties en numériques.", status=400)

        # Vérification si les valeurs sont NAN
        if df[colonne].isna().all(): 
            return HttpResponse(f"Toutes les valeurs de la colonne '{colonne}' sont NaN.", status=400)

        # colonne = request.POST.get('colonne')
        taille_echantillon = request.POST.get('taille_echantillon')
        h0_comparateur = request.POST.get('h0_comparateur')
        h0_valeur = request.POST.get('h0_valeur')
        ha_comparateur = request.POST.get('ha_comparateur')
        ha_valeur = request.POST.get('ha_valeur')
        alpha = request.POST.get('alpha')

        #---------------------------------------------------------------------------------------------------------------------
        
        # Conversion
        taille_echantillon = int(taille_echantillon)
        h0_valeur = float(h0_valeur)
        alpha = float(alpha)
        h0_comparateur = str(h0_comparateur)
        ha_comparateur = str(ha_comparateur)

        # Choix du test en fonction de la taille de l'échantillon
        # test = 'Z' if taille_echantillon >= 30 else 'T'

        if taille_echantillon >= 30 :

            test = 'Z'
            # Conversion de la liste en un tableau numpy
            valeurs_colonne_np = np.array(valeurs_colonne)

            # Extraction d'un échantillon aléatoire
            np.random.seed(0)
            echantillon = np.random.choice(valeurs_colonne_np, taille_echantillon, replace=False)

            # Calculer la moyenne de l'échantillon
            moy = (np.mean(echantillon))

            # Calculer l'écart-type de l'échantillon (utiliser la population std dev si connue)
            ecart_type = (np.std(echantillon, ddof=1))  # 'ddof=1' pour l'échantillon, utilisez 'ddof=0' pour la population

            # Calculer la statistique de test Z
            Z = (moy - h0_valeur) / (ecart_type / np.sqrt(taille_echantillon))

            # Déterminer le côté du test basé sur l'opérateur
            if ha_comparateur in ['=', '!=']:
            
                # Déterminer les scores Z critiques pour un test bilatéral
                Z_critique_negatif = norm.ppf(alpha / 2)  # Score Z critique à gauche
                Z_critique_positif = -Z_critique_negatif   # Score Z critique à droite (distribution symétrique)

                # Calculer la p-value pour un test bilatéral
                p_value = 2 * (1 - norm.cdf(np.abs(Z)))

                # Prendre une décision basée sur la p-value
                h0_rejected = p_value <= alpha

                context = {
                    'z_score': Z,
                    'z_critique_negatif': Z_critique_negatif,
                    'z_critique_positif': Z_critique_positif,
                    'p_value': p_value,
                    'h0_rejected': h0_rejected,
                    'image_base64': plot_bilateral(test, Z, Z_critique_negatif, Z_critique_positif, alpha, h0_rejected, p_value)
                }
                
                return render(request, 'resultat_test.html', context)

            elif ha_comparateur in ['>=', '>']:

                Z_critique = norm.ppf(1 - alpha)  # Score Z critique à droite
                p_value = 1 - norm.cdf(Z)
                h0_rejected = p_value <= alpha # Z > Z_critique

                context = {
                    'z_score': Z,
                    'z_critique': Z_critique,
                    'p_value': p_value,
                    'h0_rejected': h0_rejected,
                    'image_base64': plot_unilateral_droit(test, Z, Z_critique, alpha, h0_rejected, p_value)
                }

                return render(request, 'resultat_test.html', context)

            elif ha_comparateur in ['<=', '<']:

                Z_critique = norm.ppf(alpha)  # Score Z critique à gauche
                p_value = norm.cdf(Z)
                h0_rejected = p_value <= alpha # Z < Z_critique

                context = {
                    'z_score': Z,
                    'z_critique': Z_critique,
                    'p_value': p_value,
                    'h0_rejected': h0_rejected,
                    'image_base64': plot_unilateral_gauche(test, Z, Z_critique, alpha, h0_rejected, p_value)
                }

                return render(request, 'resultat_test.html', context)

            else:
                response_content = f"Colonne: {valeurs_colonne}, Taille échantillon: {taille_echantillon}, H0: µ {h0_comparateur} {h0_valeur}, HA: µ {ha_comparateur} {ha_valeur}, Alpha: {alpha}"
                return HttpResponse(response_content)
            
        else:
            test = 'T' 

            # Conversion de la liste en un tableau numpy
            valeurs_colonne_np = np.array(valeurs_colonne)

            # Extraction d'un échantillon aléatoire
            np.random.seed(0)
            echantillon = np.random.choice(valeurs_colonne_np, taille_echantillon, replace=False)

            # Calculer la moyenne de l'échantillon
            moy = (np.mean(echantillon))

            # Calculer l'écart-type de l'échantillon (utiliser la population std dev si connue)
            ecart_type = (np.std(echantillon, ddof=1))  # 'ddof=1' pour l'échantillon, utilisez 'ddof=0' pour la population

            # Calculer la statistique de test T et les degrés de liberté
            T = (moy - h0_valeur) / (ecart_type / np.sqrt(taille_echantillon))
            dofl = taille_echantillon - 1

            if ha_comparateur in ['=', '!=']:
            
                # Déterminer les scores T critiques pour un test bilatéral
                T_critique_negatif = t.ppf(alpha / 2, dofl)
                T_critique_positif = t.ppf(1 - alpha / 2, dofl)

                # Calculer la p-value pour un test bilatéral
                p_value = 2 * (1 - t.cdf(abs(T), dofl))

                # Prendre une décision basée sur la p-value

final/analyse/templates/affichage.html
<!DOCTYPE html>
<html>
<head>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    body {
      background-color: #add8e6; /* Your existing background color */
      background-image: url("{% static 'background1.jpg' %}"); 
  }

  form {
      width: 50%;
      margin: 50px auto;
      padding: 30px;
      border: 1px solid #ddd;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);
  }

  label {
      display: block;
      margin-bottom: 10px;
      font-size: 16px;
      color: #333;
  }

  input[type="text"],
  input[type="file"] {
      width: calc(100% - 22px);
      padding: 10px;
      margin-bottom: 15px;
      border: 1px solid #ccc;
      border-radius: 5px;
      font-size: 16px;
  }

  input[type="checkbox"] {
      margin-bottom: 15px;
  }

  input[type="submit"] {
      background-color: #007bff;
      color: white;
      padding: 15px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      font-size: 18px;
      transition: background-color 0.3s;
  }

  input[type="submit"]:hover {
      background-color: #0056b3;
  }
  .result-container {
          width: 50%;
          margin: 50px auto;
          padding: 30px;
          border: 1px solid #fff; /* White border */
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
          text-align: center; /* Center the text */
      }

      /* CSS for the result heading */
      .result-container h4 {
          color: #007bff; /* Blue color for the heading */
      }

</style>

</head>
<body>
    <h1>Aperçu du Fichier</h1>

    <div>
        {{ df_html | safe }}
    </div>

    <div>
        
        <form method="post" action="{% url 'analyse:appliquer_test_statistique' %}">
            {% csrf_token %}

            <!-- <div>
                {{ checkboxes | safe }}
            </div> -->

            <div>
                {{ radio_buttons | safe }}
            </div>

            <!-- <div>
                <select name="choix_graphe">
                    {% for nom_graphe in noms_graphes %}
                    <option value="{{ nom_graphe }}">{{ nom_graphe }}</option>
                    {% endfor %}
                </select>
            </div> -->

            <div>
                <label for="taille_echantillon">Taille de l'échantillon:</label>
                <input type="number" name="taille_echantillon" id="taille_echantillon" min="1" required>
            </div>

            <div>
                <!-- Hypothèses -->
                <label for="h0_comparateur">H0: µ</label>
                <select name="h0_comparateur">
                    {% for operateur in operateurs %}
                    <option value="{{ operateur }}">{{ operateur }}</option>
                    {% endfor %}
                </select>
                <input type="number" name="h0_valeur" required step="0.001">
            </div>

            <div>
                <label for="ha_comparateur">HA: µ</label>
                <select name="ha_comparateur">
                    {% for operateur in operateurs %}
                    <option value="{{ operateur }}">{{ operateur }}</option>
                    {% endfor %}
                </select>
                <input type="number" name="ha_valeur" required step="0.001">
            </div>

            <div>
                <!-- Seuil de Signification -->
                <label for="alpha">Seuil de signification (alpha):</label>
                <input type="number" name="alpha" min="0.01" max="0.05" step="0.01" required>
            </div>

            <div>
                <button type="submit" name="submit_choix">Confirmer</button>
            </div>
            
        </form>
    </div>
</body>
{% endblock %}
</html>

final/analyse/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Django Project{% endblock %}</title>
    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif; /* Choisissez la police de caractères de votre choix */
        }
    
        nav {
                background-color: lightblue;
                padding: 15px;
                text-align: center;
            }

            nav ul {
                list-style: none;
                margin: 0;
                padding: 0;
            }

            nav ul li {
                display: inline;
                margin-right: 30px; /* Ajout d'une marge à droite pour séparer les liens */
            }

            nav a {
                text-decoration: none;
                color: black;
                font-weight: bold;
                font-size: 18px;
            }

    
        div {
            padding: 20px;
        }
    </style>
    
</head>
<body>

<nav>
    <ul>
        <li><a href="{% url 'calcule:statistics' %}">calcule statistique</a></li>
        <li><a href="{% url 'matapp:upload' %}">visualisation des données</a></li>
        <li><a href="{% url 'analyse:importer_fichier2' %}">test des hypothèses</a></li>
        <li><a href="{% url 'proba:upload_file' %}">loi de probabilité</a></li>
    </ul>
</nav>

<div>
    {% block content %}{% endblock %}
</div>

</body>
</html>

final/analyse/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Ma Page Web{% endblock %}</title>
    {% load static %}
    <style>
        body {
          background-color: #add8e6; /* Your existing background color */
          background-image: url("{% static 'background1.jpg' %}"); 
      }

      form {
          width: 50%;
          margin: 50px auto;
          padding: 30px;
          border: 1px solid #ddd;
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);
      }

      label {
          display: block;
          margin-bottom: 10px;
          font-size: 16px;
          color: #333;
      }

      input[type="text"],
      input[type="file"] {
          width: calc(100% - 22px);
          padding: 10px;
          margin-bottom: 15px;
          border: 1px solid #ccc;
          border-radius: 5px;
          font-size: 16px;
      }

      input[type="checkbox"] {
          margin-bottom: 15px;
      }

      input[type="submit"] {
          background-color: #007bff;
          color: white;
          padding: 15px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          font-size: 18px;
          transition: background-color 0.3s;
      }

      input[type="submit"]:hover {
          background-color: #0056b3;
      }
      .result-container {
              width: 50%;
              margin: 50px auto;
              padding: 30px;
              border: 1px solid #fff; /* White border */
              background-color: #fff;
              border-radius: 10px;
              box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
              text-align: center; /* Center the text */
          }

          /* CSS for the result heading */
          .result-container h4 {
              color: #007bff; /* Blue color for the heading */
          }

</style>
    
</head>
<body>
    
    {% block content %}
    
    {% endblock %}

</body>
</html>

final/analyse/templates/base_visualisation.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Visualisation{% endblock %}</title>
    {% extends 'base.html' %}
</head>
<body>
    <header>
        <!-- Contenu de l'en-tête -->
    </header>

    <main>
        {% block content %}
        <!-- Contenu spécifique à chaque page de visualisation -->
        {% endblock %}
    </main>

    <footer>
        <!-- Contenu du pied de page -->
    </footer>
</body>
</html>

final/analyse/templates/graphe_line_plot.html
<!DOCTYPE html>
<html>
<head>
{% extends 'base.html' %}

{% block title %}Visualisation du Graphique{% endblock %}
{% load static %}
    
    {% block content %}
    <style>
                  body {
                    background-color: #add8e6; /* Your existing background color */
                    background-image: url("{% static 'background1.jpg' %}"); 
                }

                form {
                    width: 50%;
                    margin: 50px auto;
                    padding: 30px;
                    border: 1px solid #ddd;
                    background-color: #fff;
                    border-radius: 10px;
                    box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);
                }

                label {
                    display: block;
                    margin-bottom: 10px;
                    font-size: 16px;
                    color: #333;
                }

                input[type="text"],
                input[type="file"] {
                    width: calc(100% - 22px);
                    padding: 10px;
                    margin-bottom: 15px;
                    border: 1px solid #ccc;
                    border-radius: 5px;
                    font-size: 16px;
                }

                input[type="checkbox"] {
                    margin-bottom: 15px;
                }

                input[type="submit"] {
                    background-color: #007bff;
                    color: white;
                    padding: 15px 20px;
                    border: none;
                    border-radius: 5px;
                    cursor: pointer;
                    font-size: 18px;
                    transition: background-color 0.3s;
                }

                input[type="submit"]:hover {
                    background-color: #0056b3;
                }
                .result-container {
                        width: 50%;
                        margin: 50px auto;
                        padding: 30px;
                        border: 1px solid #fff; /* White border */
                        background-color: #fff;
                        border-radius: 10px;
                        box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
                        text-align: center; /* Center the text */
                    }

                    /* CSS for the result heading */
                    .result-container h4 {
                        color: #007bff; /* Blue color for the heading */
                    }

    </style>
</head>
<body>
    <h1>Trace de ligne (Line Plot)</h1>
    {% if image_base64 %}
        <img src="data:image/png;base64,{{ image_base64 | safe }}" alt="Graphique">
    {% else %}
        <p>Aucune image à afficher.</p>
    {% endif %}
</body>
{% endblock %}
</html>

final/analyse/templates/resultat_test.html
<!DOCTYPE html>
<html>
<head>
    <title>Résultats du Test Statistique</title>
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <style>
        body {
          background-color: #add8e6; /* Your existing background color */
          background-image: url("{% static 'background1.jpg' %}"); 
      }

      form {
          width: 50%;
          margin: 50px auto;
          padding: 30px;
          border: 1px solid #ddd;
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);
      }

      label {
          display: block;
          margin-bottom: 10px;
          font-size: 16px;
          color: #333;
      }

      input[type="text"],
      input[type="file"] {
          width: calc(100% - 22px);
          padding: 10px;
          margin-bottom: 15px;
          border: 1px solid #ccc;
          border-radius: 5px;
          font-size: 16px;
      }

      input[type="checkbox"] {
          margin-bottom: 15px;
      }

      input[type="submit"] {
          background-color: #007bff;
          color: white;
          padding: 15px 20px;
          border: none;
          border-radius: 5px;
          cursor: pointer;
          font-size: 18px;
          transition: background-color 0.3s;
      }

      input[type="submit"]:hover {
          background-color: #0056b3;
      }
      .result-container {
              width: 50%;
              margin: 50px auto;
              padding: 30px;
              border: 1px solid #fff; /* White border */
              background-color: #fff;
              border-radius: 10px;
              box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
              text-align: center; /* Center the text */
          }

          /* CSS for the result heading */
          .result-container h4 {
              color: #007bff; /* Blue color for the heading */
          }

</style>
</head>
<body>
    
    <h1>Résultats du Test Statistique</h1>
    {% if image_base64 %}
        <img src="data:image/png;base64,{{ image_base64 }}" alt="Graphique du Test Statistique">
    {% else %}
        <p>Aucun graphique à afficher.</p>
    {% endif %}
    <!-- Autres éléments du template -->
    
</body>
{% endblock %}
</html>

final/analyse/templates/upload1.html
<!DOCTYPE html>
<html>
<head>
{% extends 'base.html' %}
{% load static %}
{% block title %}Upload de fichier{% endblock %}

{% block content %}
<style>
    body {
      background-color: #add8e6; /* Your existing background color */
      background-image: url("{% static 'background1.jpg' %}"); 
  }

  form {
      width: 50%;
      margin: 50px auto;
      padding: 30px;
      border: 1px solid #ddd;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 0 10px rgba(0, 0, 255, 0.7);
  }

  label {
      display: block;
      margin-bottom: 10px;
      font-size: 16px;
      color: #333;
  }

  input[type="text"],
  input[type="file"] {
      width: calc(100% - 22px);
      padding: 10px;
      margin-bottom: 15px;
      border: 1px solid #ccc;
      border-radius: 5px;
      font-size: 16px;
  }

  input[type="checkbox"] {
      margin-bottom: 15px;
  }

  input[type="submit"] {
      background-color: #007bff;
      color: white;
      padding: 15px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      font-size: 18px;
      transition: background-color 0.3s;
  }

  input[type="submit"]:hover {
      background-color: #0056b3;
  }
  .result-container {
          width: 50%;
          margin: 50px auto;
          padding: 30px;
          border: 1px solid #fff; /* White border */
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 0 10px rgba(0, 0, 255, 0.7); /* Blue shadow */
          text-align: center; /* Center the text */
      }

      /* CSS for the result heading */
      .result-container h4 {
          color: #007bff; /* Blue color for the heading */
      }

</style>
</head>
<body>
    <h1>Importer un Fichier</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="fichier">
        <button type="submit">Importer</button>
    </form>

</body>
{% endblock %}
</html>